[global]
# disableWidgetStateDuplicationWarning = false
# showWarningOnDirectExecution = true

[logger]
# level = "info"
# messageFormat = "%(asctime)s %(message)s"

[client]
# showErrorDetails = "full"
# toolbarMode = "auto"
# showSidebarNavigation = true

[runner]
# magicEnabled = true
# fastReruns = true
# enforceSerializableSessionState = false
# enumCoercion = "nameOnly"

[server]
port = 8501

[browser]
# serverAddress = "localhost"
# gatherUsageStats = true
# serverPort = 8501

[mapbox]
# token = ""

[theme]
base="light"
primaryColor="#A8D5BA"
backgroundColor="#F5FFF8"
secondaryBackgroundColor="#D7F0DF"
textColor="#304038"
font="sans-serif"
# codeFont =
# codeFontSize =
# headingFont =
# fontFaces =
# baseRadius =
# buttonRadius =
# borderColor =
# dataframeBorderColor =
# showWidgetBorder =
# baseFontSize =
# showSidebarBorder =

[theme.sidebar]
# primaryColor =
# backgroundColor =
# secondaryBackgroundColor =
# textColor =
# linkColor =
# codeBackgroundColor =
# font =
# codeFont =
# codeFontSize =
# headingFont =
# baseRadius =
# buttonRadius =
# borderColor =
# dataframeBorderColor =
# showWidgetBorder =

[secrets]
# files = [ "C:\\Users\\24i1004\\.streamlit\\secrets.toml", "C:\\Users\24i1004\\.streamlit\\secrets.toml",]